// Each entry: [character, toned pinyin, English meaning]
type CharEntry = [string, string, string];

// Maps toneless pinyin syllable → most common characters (frequency-ordered)
export const PINYIN_MAP: Record<string, CharEntry[]> = {
  a: [['啊', 'a', 'ah'], ['阿', 'ā', 'prefix']],
  ai: [['爱', 'ài', 'love'], ['哎', 'āi', 'hey'], ['矮', 'ǎi', 'short'], ['癌', 'ái', 'cancer']],
  an: [['安', 'ān', 'peace'], ['暗', 'àn', 'dark'], ['按', 'àn', 'press'], ['岸', 'àn', 'shore']],
  ang: [['昂', 'áng', 'raise']],
  ao: [['奥', 'ào', 'profound'], ['熬', 'áo', 'endure'], ['傲', 'ào', 'proud']],
  ba: [['八', 'bā', 'eight'], ['吧', 'ba', 'particle'], ['把', 'bǎ', 'hold'], ['爸', 'bà', 'dad'], ['拔', 'bá', 'pull']],
  bai: [['白', 'bái', 'white'], ['百', 'bǎi', 'hundred'], ['拜', 'bài', 'worship'], ['败', 'bài', 'defeat']],
  ban: [['半', 'bàn', 'half'], ['班', 'bān', 'class'], ['办', 'bàn', 'handle'], ['搬', 'bān', 'move'], ['板', 'bǎn', 'board']],
  bang: [['帮', 'bāng', 'help'], ['棒', 'bàng', 'stick'], ['绑', 'bǎng', 'bind']],
  bao: [['包', 'bāo', 'wrap'], ['报', 'bào', 'report'], ['抱', 'bào', 'hug'], ['宝', 'bǎo', 'treasure'], ['饱', 'bǎo', 'full']],
  bei: [['北', 'běi', 'north'], ['被', 'bèi', 'by/quilt'], ['杯', 'bēi', 'cup'], ['背', 'bèi', 'back'], ['悲', 'bēi', 'sad']],
  ben: [['本', 'běn', 'root/book'], ['笨', 'bèn', 'stupid'], ['奔', 'bēn', 'run']],
  bi: [['比', 'bǐ', 'compare'], ['笔', 'bǐ', 'pen'], ['必', 'bì', 'must'], ['鼻', 'bí', 'nose'], ['闭', 'bì', 'close']],
  bian: [['边', 'biān', 'side'], ['变', 'biàn', 'change'], ['便', 'biàn', 'convenient'], ['遍', 'biàn', 'everywhere']],
  biao: [['表', 'biǎo', 'surface/watch'], ['标', 'biāo', 'mark']],
  bie: [['别', 'bié', "don't/other"], ['憋', 'biē', 'hold back']],
  bin: [['宾', 'bīn', 'guest']],
  bing: [['病', 'bìng', 'sick'], ['冰', 'bīng', 'ice'], ['兵', 'bīng', 'soldier'], ['并', 'bìng', 'and/also']],
  bo: [['波', 'bō', 'wave'], ['播', 'bō', 'broadcast'], ['伯', 'bó', 'uncle'], ['博', 'bó', 'broad']],
  bu: [['不', 'bù', 'not'], ['步', 'bù', 'step'], ['部', 'bù', 'part'], ['布', 'bù', 'cloth'], ['补', 'bǔ', 'mend']],
  ca: [['擦', 'cā', 'wipe']],
  cai: [['才', 'cái', 'talent/just'], ['菜', 'cài', 'vegetable'], ['猜', 'cāi', 'guess'], ['材', 'cái', 'material'], ['彩', 'cǎi', 'color']],
  can: [['参', 'cān', 'participate'], ['餐', 'cān', 'meal'], ['残', 'cán', 'cruel'], ['惨', 'cǎn', 'tragic']],
  cang: [['藏', 'cáng', 'hide']],
  cao: [['草', 'cǎo', 'grass'], ['操', 'cāo', 'operate']],
  ce: [['厕', 'cè', 'toilet'], ['测', 'cè', 'measure'], ['册', 'cè', 'volume'], ['策', 'cè', 'strategy']],
  cha: [['茶', 'chá', 'tea'], ['查', 'chá', 'check'], ['差', 'chà', 'lack/poor'], ['插', 'chā', 'insert']],
  chai: [['拆', 'chāi', 'tear down']],
  chan: [['产', 'chǎn', 'produce'], ['缠', 'chán', 'wrap']],
  chang: [['长', 'cháng', 'long'], ['常', 'cháng', 'often'], ['唱', 'chàng', 'sing'], ['场', 'chǎng', 'field']],
  chao: [['超', 'chāo', 'super'], ['朝', 'cháo', 'toward'], ['吵', 'chǎo', 'noisy'], ['炒', 'chǎo', 'stir-fry']],
  che: [['车', 'chē', 'car'], ['扯', 'chě', 'pull']],
  chen: [['陈', 'chén', 'display/Chen'], ['沉', 'chén', 'sink'], ['晨', 'chén', 'morning'], ['衬', 'chèn', 'lining']],
  cheng: [['成', 'chéng', 'become'], ['城', 'chéng', 'city'], ['程', 'chéng', 'journey'], ['称', 'chēng', 'call'], ['承', 'chéng', 'bear']],
  chi: [['吃', 'chī', 'eat'], ['池', 'chí', 'pond'], ['尺', 'chǐ', 'ruler'], ['迟', 'chí', 'late'], ['持', 'chí', 'hold']],
  chong: [['冲', 'chōng', 'rush'], ['充', 'chōng', 'fill'], ['虫', 'chóng', 'insect'], ['重', 'chóng', 'repeat']],
  chou: [['抽', 'chōu', 'draw out'], ['丑', 'chǒu', 'ugly'], ['臭', 'chòu', 'stinky']],
  chu: [['出', 'chū', 'exit'], ['初', 'chū', 'first'], ['除', 'chú', 'remove'], ['处', 'chù', 'place'], ['楚', 'chǔ', 'clear']],
  chuan: [['穿', 'chuān', 'wear'], ['传', 'chuán', 'pass'], ['船', 'chuán', 'ship'], ['串', 'chuàn', 'string']],
  chuang: [['床', 'chuáng', 'bed'], ['窗', 'chuāng', 'window'], ['创', 'chuàng', 'create'], ['闯', 'chuǎng', 'rush']],
  chui: [['吹', 'chuī', 'blow']],
  chun: [['春', 'chūn', 'spring'], ['纯', 'chún', 'pure']],
  ci: [['次', 'cì', 'time/next'], ['词', 'cí', 'word'], ['此', 'cǐ', 'this'], ['刺', 'cì', 'thorn']],
  cong: [['从', 'cóng', 'from'], ['聪', 'cōng', 'clever']],
  cu: [['粗', 'cū', 'thick'], ['醋', 'cù', 'vinegar']],
  cun: [['村', 'cūn', 'village'], ['存', 'cún', 'exist']],
  cuo: [['错', 'cuò', 'wrong']],
  da: [['大', 'dà', 'big'], ['打', 'dǎ', 'hit'], ['达', 'dá', 'reach'], ['答', 'dá', 'answer']],
  dai: [['带', 'dài', 'carry'], ['代', 'dài', 'generation'], ['待', 'dài', 'wait'], ['袋', 'dài', 'bag'], ['戴', 'dài', 'wear']],
  dan: [['但', 'dàn', 'but'], ['单', 'dān', 'single'], ['蛋', 'dàn', 'egg'], ['淡', 'dàn', 'light'], ['担', 'dān', 'carry']],
  dang: [['当', 'dāng', 'serve as'], ['党', 'dǎng', 'party'], ['挡', 'dǎng', 'block']],
  dao: [['到', 'dào', 'arrive'], ['道', 'dào', 'way'], ['刀', 'dāo', 'knife'], ['倒', 'dào', 'fall'], ['岛', 'dǎo', 'island']],
  de: [['的', 'de', 'possessive'], ['得', 'dé', 'get'], ['德', 'dé', 'virtue']],
  dei: [['得', 'děi', 'must']],
  deng: [['等', 'děng', 'wait'], ['灯', 'dēng', 'lamp'], ['登', 'dēng', 'climb']],
  di: [['地', 'dì', 'earth'], ['低', 'dī', 'low'], ['第', 'dì', 'ordinal'], ['弟', 'dì', 'brother'], ['底', 'dǐ', 'bottom'], ['敌', 'dí', 'enemy']],
  dian: [['点', 'diǎn', 'point'], ['电', 'diàn', 'electric'], ['店', 'diàn', 'shop'], ['典', 'diǎn', 'canon']],
  diao: [['掉', 'diào', 'drop'], ['调', 'diào', 'tune'], ['钓', 'diào', 'fish']],
  ding: [['定', 'dìng', 'fix'], ['丁', 'dīng', 'nail'], ['顶', 'dǐng', 'top']],
  diu: [['丢', 'diū', 'lose']],
  dong: [['东', 'dōng', 'east'], ['冬', 'dōng', 'winter'], ['动', 'dòng', 'move'], ['懂', 'dǒng', 'understand'], ['洞', 'dòng', 'hole']],
  dou: [['都', 'dōu', 'all'], ['斗', 'dòu', 'fight'], ['豆', 'dòu', 'bean']],
  du: [['读', 'dú', 'read'], ['度', 'dù', 'degree'], ['独', 'dú', 'alone'], ['肚', 'dù', 'belly'], ['堵', 'dǔ', 'block']],
  duan: [['短', 'duǎn', 'short'], ['段', 'duàn', 'section'], ['断', 'duàn', 'break']],
  dui: [['对', 'duì', 'correct'], ['队', 'duì', 'team']],
  duo: [['多', 'duō', 'many'], ['朵', 'duǒ', 'flower'], ['躲', 'duǒ', 'hide']],
  e: [['饿', 'è', 'hungry'], ['恶', 'è', 'evil']],
  ei: [['诶', 'éi', 'hey']],
  en: [['嗯', 'en', 'hmm']],
  er: [['二', 'èr', 'two'], ['而', 'ér', 'and'], ['耳', 'ěr', 'ear'], ['儿', 'ér', 'child']],
  fa: [['发', 'fā', 'send'], ['法', 'fǎ', 'law'], ['罚', 'fá', 'punish']],
  fan: [['饭', 'fàn', 'rice/meal'], ['反', 'fǎn', 'opposite'], ['翻', 'fān', 'turn'], ['烦', 'fán', 'annoyed'], ['犯', 'fàn', 'commit']],
  fang: [['方', 'fāng', 'square'], ['放', 'fàng', 'put'], ['房', 'fáng', 'room'], ['防', 'fáng', 'prevent'], ['访', 'fǎng', 'visit']],
  fei: [['飞', 'fēi', 'fly'], ['非', 'fēi', 'not'], ['费', 'fèi', 'cost'], ['肥', 'féi', 'fat']],
  fen: [['分', 'fēn', 'divide'], ['份', 'fèn', 'portion'], ['粉', 'fěn', 'powder'], ['奋', 'fèn', 'strive']],
  feng: [['风', 'fēng', 'wind'], ['丰', 'fēng', 'rich'], ['封', 'fēng', 'seal'], ['蜂', 'fēng', 'bee'], ['疯', 'fēng', 'crazy']],
  fu: [['父', 'fù', 'father'], ['服', 'fú', 'clothes'], ['福', 'fú', 'fortune'], ['富', 'fù', 'rich'], ['付', 'fù', 'pay'], ['复', 'fù', 'repeat'], ['夫', 'fū', 'husband']],
  ga: [['嘎', 'gā', 'quack']],
  gai: [['该', 'gāi', 'should'], ['改', 'gǎi', 'change'], ['盖', 'gài', 'cover']],
  gan: [['干', 'gàn', 'do/dry'], ['感', 'gǎn', 'feel'], ['敢', 'gǎn', 'dare'], ['赶', 'gǎn', 'chase'], ['甘', 'gān', 'sweet']],
  gang: [['刚', 'gāng', 'just'], ['钢', 'gāng', 'steel'], ['港', 'gǎng', 'harbor']],
  gao: [['高', 'gāo', 'tall'], ['告', 'gào', 'tell'], ['搞', 'gǎo', 'do']],
  ge: [['个', 'gè', 'measure word'], ['歌', 'gē', 'song'], ['哥', 'gē', 'brother'], ['各', 'gè', 'each'], ['隔', 'gé', 'separate']],
  gei: [['给', 'gěi', 'give']],
  gen: [['跟', 'gēn', 'follow'], ['根', 'gēn', 'root']],
  geng: [['更', 'gèng', 'more']],
  gong: [['工', 'gōng', 'work'], ['公', 'gōng', 'public'], ['共', 'gòng', 'common'], ['功', 'gōng', 'merit']],
  gou: [['狗', 'gǒu', 'dog'], ['够', 'gòu', 'enough'], ['构', 'gòu', 'construct']],
  gu: [['古', 'gǔ', 'ancient'], ['故', 'gù', 'reason'], ['骨', 'gǔ', 'bone'], ['鼓', 'gǔ', 'drum'], ['顾', 'gù', 'look after']],
  gua: [['刮', 'guā', 'scrape'], ['瓜', 'guā', 'melon'], ['挂', 'guà', 'hang']],
  guai: [['怪', 'guài', 'strange'], ['乖', 'guāi', 'obedient']],
  guan: [['关', 'guān', 'close'], ['管', 'guǎn', 'manage'], ['官', 'guān', 'official'], ['观', 'guān', 'view'], ['馆', 'guǎn', 'hall']],
  guang: [['光', 'guāng', 'light'], ['广', 'guǎng', 'wide'], ['逛', 'guàng', 'stroll']],
  gui: [['贵', 'guì', 'expensive'], ['归', 'guī', 'return'], ['鬼', 'guǐ', 'ghost'], ['规', 'guī', 'rule']],
  gun: [['滚', 'gǔn', 'roll']],
  guo: [['国', 'guó', 'country'], ['过', 'guò', 'pass'], ['果', 'guǒ', 'fruit'], ['锅', 'guō', 'pot']],
  ha: [['哈', 'hā', 'ha']],
  hai: [['还', 'hái', 'still'], ['海', 'hǎi', 'sea'], ['孩', 'hái', 'child'], ['害', 'hài', 'harm']],
  han: [['汉', 'hàn', 'Chinese'], ['寒', 'hán', 'cold'], ['喊', 'hǎn', 'shout'], ['汗', 'hàn', 'sweat'], ['含', 'hán', 'contain']],
  hang: [['行', 'háng', 'row'], ['航', 'háng', 'navigate']],
  hao: [['好', 'hǎo', 'good'], ['号', 'hào', 'number'], ['浩', 'hào', 'vast'], ['耗', 'hào', 'consume']],
  he: [['和', 'hé', 'and'], ['河', 'hé', 'river'], ['喝', 'hē', 'drink'], ['合', 'hé', 'combine'], ['何', 'hé', 'what'], ['黑', 'hēi', 'black']],
  hei: [['黑', 'hēi', 'black']],
  hen: [['很', 'hěn', 'very'], ['恨', 'hèn', 'hate'], ['狠', 'hěn', 'fierce']],
  heng: [['横', 'héng', 'horizontal']],
  hong: [['红', 'hóng', 'red'], ['洪', 'hóng', 'flood']],
  hou: [['后', 'hòu', 'after'], ['厚', 'hòu', 'thick'], ['候', 'hòu', 'wait'], ['猴', 'hóu', 'monkey']],
  hu: [['湖', 'hú', 'lake'], ['胡', 'hú', 'nonsense'], ['虎', 'hǔ', 'tiger'], ['护', 'hù', 'protect'], ['互', 'hù', 'mutual'], ['户', 'hù', 'household'], ['呼', 'hū', 'call']],
  hua: [['花', 'huā', 'flower'], ['画', 'huà', 'draw'], ['话', 'huà', 'speech'], ['化', 'huà', 'change'], ['华', 'huá', 'splendid']],
  huai: [['坏', 'huài', 'bad'], ['怀', 'huái', 'bosom']],
  huan: [['还', 'huán', 'return'], ['换', 'huàn', 'exchange'], ['欢', 'huān', 'happy'], ['环', 'huán', 'ring']],
  huang: [['黄', 'huáng', 'yellow'], ['皇', 'huáng', 'emperor'], ['慌', 'huāng', 'panic']],
  hui: [['会', 'huì', 'can/meet'], ['回', 'huí', 'return'], ['灰', 'huī', 'gray'], ['汇', 'huì', 'collect']],
  hun: [['婚', 'hūn', 'marriage'], ['混', 'hùn', 'mix']],
  huo: [['火', 'huǒ', 'fire'], ['活', 'huó', 'live'], ['或', 'huò', 'or'], ['货', 'huò', 'goods']],
  ji: [['几', 'jǐ', 'how many'], ['机', 'jī', 'machine'], ['鸡', 'jī', 'chicken'], ['记', 'jì', 'remember'], ['急', 'jí', 'urgent'], ['集', 'jí', 'collect'], ['己', 'jǐ', 'self'], ['计', 'jì', 'plan'], ['级', 'jí', 'level'], ['季', 'jì', 'season']],
  jia: [['家', 'jiā', 'home'], ['加', 'jiā', 'add'], ['假', 'jiǎ', 'fake'], ['价', 'jià', 'price'], ['架', 'jià', 'frame']],
  jian: [['见', 'jiàn', 'see'], ['间', 'jiān', 'between'], ['件', 'jiàn', 'piece'], ['建', 'jiàn', 'build'], ['简', 'jiǎn', 'simple'], ['剪', 'jiǎn', 'cut'], ['检', 'jiǎn', 'check']],
  jiang: [['将', 'jiāng', 'will'], ['讲', 'jiǎng', 'speak'], ['江', 'jiāng', 'river'], ['奖', 'jiǎng', 'award'], ['降', 'jiàng', 'descend']],
  jiao: [['叫', 'jiào', 'call'], ['教', 'jiāo', 'teach'], ['脚', 'jiǎo', 'foot'], ['角', 'jiǎo', 'corner'], ['交', 'jiāo', 'exchange'], ['饺', 'jiǎo', 'dumpling']],
  jie: [['姐', 'jiě', 'sister'], ['街', 'jiē', 'street'], ['接', 'jiē', 'receive'], ['节', 'jié', 'festival'], ['结', 'jié', 'tie'], ['解', 'jiě', 'solve'], ['借', 'jiè', 'borrow']],
  jin: [['今', 'jīn', 'today'], ['金', 'jīn', 'gold'], ['进', 'jìn', 'enter'], ['近', 'jìn', 'near'], ['紧', 'jǐn', 'tight'], ['尽', 'jǐn', 'exhaust'], ['仅', 'jǐn', 'only']],
  jing: [['经', 'jīng', 'pass through'], ['京', 'jīng', 'capital'], ['精', 'jīng', 'fine'], ['静', 'jìng', 'quiet'], ['景', 'jǐng', 'scene'], ['惊', 'jīng', 'surprise'], ['净', 'jìng', 'clean'], ['镜', 'jìng', 'mirror']],
  jiu: [['九', 'jiǔ', 'nine'], ['久', 'jiǔ', 'long time'], ['酒', 'jiǔ', 'wine'], ['就', 'jiù', 'then'], ['旧', 'jiù', 'old'], ['救', 'jiù', 'save']],
  ju: [['举', 'jǔ', 'raise'], ['句', 'jù', 'sentence'], ['具', 'jù', 'tool'], ['局', 'jú', 'bureau'], ['距', 'jù', 'distance']],
  juan: [['卷', 'juǎn', 'roll']],
  jue: [['觉', 'jué', 'feel'], ['决', 'jué', 'decide'], ['绝', 'jué', 'absolute']],
  jun: [['军', 'jūn', 'army'], ['均', 'jūn', 'equal']],
  ka: [['卡', 'kǎ', 'card'], ['咖', 'kā', 'coffee']],
  kai: [['开', 'kāi', 'open'], ['凯', 'kǎi', 'triumph']],
  kan: [['看', 'kàn', 'look'], ['砍', 'kǎn', 'chop']],
  kang: [['扛', 'káng', 'carry'], ['抗', 'kàng', 'resist']],
  kao: [['考', 'kǎo', 'test'], ['靠', 'kào', 'rely'], ['烤', 'kǎo', 'roast']],
  ke: [['可', 'kě', 'can'], ['课', 'kè', 'lesson'], ['客', 'kè', 'guest'], ['刻', 'kè', 'carve'], ['科', 'kē', 'science'], ['渴', 'kě', 'thirsty']],
  ken: [['肯', 'kěn', 'willing']],
  kong: [['空', 'kōng', 'empty'], ['控', 'kòng', 'control'], ['恐', 'kǒng', 'fear']],
  kou: [['口', 'kǒu', 'mouth'], ['扣', 'kòu', 'button']],
  ku: [['哭', 'kū', 'cry'], ['苦', 'kǔ', 'bitter'], ['酷', 'kù', 'cool'], ['库', 'kù', 'warehouse']],
  kua: [['夸', 'kuā', 'praise'], ['跨', 'kuà', 'stride']],
  kuai: [['快', 'kuài', 'fast'], ['块', 'kuài', 'piece']],
  kuan: [['宽', 'kuān', 'wide'], ['款', 'kuǎn', 'fund']],
  kuang: [['狂', 'kuáng', 'crazy'], ['矿', 'kuàng', 'mine']],
  kun: [['困', 'kùn', 'sleepy'], ['昆', 'kūn', 'descendant']],
  la: [['拉', 'lā', 'pull'], ['啦', 'la', 'particle'], ['辣', 'là', 'spicy']],
  lai: [['来', 'lái', 'come'], ['赖', 'lài', 'rely']],
  lan: [['蓝', 'lán', 'blue'], ['懒', 'lǎn', 'lazy'], ['兰', 'lán', 'orchid'], ['烂', 'làn', 'rotten']],
  lang: [['浪', 'làng', 'wave'], ['狼', 'láng', 'wolf']],
  lao: [['老', 'lǎo', 'old'], ['姥', 'lǎo', 'grandma'], ['劳', 'láo', 'labor']],
  le: [['了', 'le', 'particle'], ['乐', 'lè', 'happy']],
  lei: [['累', 'lèi', 'tired'], ['类', 'lèi', 'type'], ['雷', 'léi', 'thunder'], ['泪', 'lèi', 'tear']],
  leng: [['冷', 'lěng', 'cold'], ['愣', 'lèng', 'stunned']],
  li: [['里', 'lǐ', 'inside'], ['力', 'lì', 'power'], ['立', 'lì', 'stand'], ['理', 'lǐ', 'reason'], ['离', 'lí', 'leave'], ['利', 'lì', 'benefit'], ['礼', 'lǐ', 'gift'], ['李', 'lǐ', 'plum']],
  lia: [['俩', 'liǎ', 'two (people)']],
  lian: [['连', 'lián', 'connect'], ['脸', 'liǎn', 'face'], ['练', 'liàn', 'practice'], ['联', 'lián', 'unite'], ['恋', 'liàn', 'love']],
  liang: [['两', 'liǎng', 'two'], ['亮', 'liàng', 'bright'], ['凉', 'liáng', 'cool'], ['量', 'liàng', 'amount']],
  liao: [['了', 'liǎo', 'finish'], ['聊', 'liáo', 'chat'], ['料', 'liào', 'material']],
  lie: [['列', 'liè', 'row'], ['裂', 'liè', 'crack'], ['烈', 'liè', 'fierce']],
  lin: [['林', 'lín', 'forest'], ['临', 'lín', 'face'], ['邻', 'lín', 'neighbor']],
  ling: [['零', 'líng', 'zero'], ['灵', 'líng', 'spirit'], ['领', 'lǐng', 'lead'], ['令', 'lìng', 'order']],
  liu: [['六', 'liù', 'six'], ['流', 'liú', 'flow'], ['留', 'liú', 'stay']],
  long: [['龙', 'lóng', 'dragon'], ['笼', 'lóng', 'cage']],
  lou: [['楼', 'lóu', 'building'], ['漏', 'lòu', 'leak']],
  lu: [['路', 'lù', 'road'], ['录', 'lù', 'record'], ['绿', 'lǜ', 'green'], ['鹿', 'lù', 'deer'], ['露', 'lù', 'dew']],
  luan: [['乱', 'luàn', 'messy']],
  lun: [['论', 'lùn', 'discuss'], ['轮', 'lún', 'wheel']],
  luo: [['落', 'luò', 'fall'], ['罗', 'luó', 'net']],
  lv: [['绿', 'lǜ', 'green'], ['旅', 'lǚ', 'travel'], ['律', 'lǜ', 'law']],
  ma: [['妈', 'mā', 'mom'], ['马', 'mǎ', 'horse'], ['吗', 'ma', 'question'], ['麻', 'má', 'numb'], ['骂', 'mà', 'scold']],
  mai: [['买', 'mǎi', 'buy'], ['卖', 'mài', 'sell'], ['麦', 'mài', 'wheat']],
  man: [['满', 'mǎn', 'full'], ['慢', 'màn', 'slow'], ['漫', 'màn', 'overflow']],
  mang: [['忙', 'máng', 'busy'], ['盲', 'máng', 'blind']],
  mao: [['猫', 'māo', 'cat'], ['毛', 'máo', 'hair'], ['帽', 'mào', 'hat'], ['冒', 'mào', 'emit']],
  me: [['么', 'me', 'suffix']],
  mei: [['没', 'méi', 'not have'], ['美', 'měi', 'beautiful'], ['每', 'měi', 'every'], ['妹', 'mèi', 'sister'], ['梅', 'méi', 'plum']],
  men: [['门', 'mén', 'door'], ['们', 'men', 'plural']],
  meng: [['梦', 'mèng', 'dream'], ['猛', 'měng', 'fierce']],
  mi: [['米', 'mǐ', 'rice'], ['秘', 'mì', 'secret'], ['密', 'mì', 'dense'], ['迷', 'mí', 'lost']],
  mian: [['面', 'miàn', 'face/noodle'], ['免', 'miǎn', 'avoid'], ['棉', 'mián', 'cotton']],
  miao: [['秒', 'miǎo', 'second'], ['妙', 'miào', 'wonderful'], ['苗', 'miáo', 'sprout']],
  min: [['民', 'mín', 'people'], ['敏', 'mǐn', 'sensitive']],
  ming: [['明', 'míng', 'bright'], ['名', 'míng', 'name'], ['命', 'mìng', 'life']],
  mo: [['摸', 'mō', 'touch'], ['末', 'mò', 'end'], ['磨', 'mó', 'grind'], ['墨', 'mò', 'ink'], ['默', 'mò', 'silent'], ['莫', 'mò', 'do not']],
  mou: [['某', 'mǒu', 'certain']],
  mu: [['木', 'mù', 'wood'], ['目', 'mù', 'eye'], ['母', 'mǔ', 'mother'], ['牧', 'mù', 'herd']],
  na: [['那', 'nà', 'that'], ['拿', 'ná', 'take'], ['哪', 'nǎ', 'which']],
  nai: [['奶', 'nǎi', 'milk'], ['耐', 'nài', 'endure']],
  nan: [['男', 'nán', 'male'], ['南', 'nán', 'south'], ['难', 'nán', 'difficult']],
  nao: [['脑', 'nǎo', 'brain'], ['闹', 'nào', 'noisy']],
  ne: [['呢', 'ne', 'particle']],
  nei: [['内', 'nèi', 'inside']],
  neng: [['能', 'néng', 'can']],
  ni: [['你', 'nǐ', 'you'], ['泥', 'ní', 'mud'], ['逆', 'nì', 'against'], ['腻', 'nì', 'greasy']],
  nian: [['年', 'nián', 'year'], ['念', 'niàn', 'read']],
  niang: [['娘', 'niáng', 'mother']],
  niao: [['鸟', 'niǎo', 'bird'], ['尿', 'niào', 'urine']],
  nin: [['您', 'nín', 'you (polite)']],
  niu: [['牛', 'niú', 'cow'], ['扭', 'niǔ', 'twist']],
  nong: [['农', 'nóng', 'farm'], ['浓', 'nóng', 'thick']],
  nu: [['女', 'nǚ', 'female'], ['怒', 'nù', 'angry'], ['努', 'nǔ', 'strive']],
  nuan: [['暖', 'nuǎn', 'warm']],
  o: [['哦', 'ó', 'oh']],
  ou: [['偶', 'ǒu', 'occasionally'], ['欧', 'ōu', 'Europe']],
  pa: [['怕', 'pà', 'fear'], ['爬', 'pá', 'climb'], ['拍', 'pāi', 'clap']],
  pai: [['拍', 'pāi', 'clap'], ['排', 'pái', 'row'], ['派', 'pài', 'faction']],
  pan: [['盘', 'pán', 'plate'], ['判', 'pàn', 'judge'], ['盼', 'pàn', 'hope']],
  pang: [['旁', 'páng', 'beside'], ['胖', 'pàng', 'fat']],
  pao: [['跑', 'pǎo', 'run'], ['泡', 'pào', 'bubble'], ['炮', 'pào', 'cannon']],
  pei: [['陪', 'péi', 'accompany'], ['配', 'pèi', 'match']],
  pen: [['盆', 'pén', 'basin']],
  peng: [['朋', 'péng', 'friend'], ['碰', 'pèng', 'touch'], ['捧', 'pěng', 'hold']],
  pi: [['皮', 'pí', 'skin'], ['批', 'pī', 'batch'], ['脾', 'pí', 'spleen'], ['屁', 'pì', 'fart'], ['匹', 'pǐ', 'measure word']],
  pian: [['片', 'piàn', 'slice'], ['骗', 'piàn', 'cheat'], ['便', 'pián', 'cheap'], ['篇', 'piān', 'article']],
  piao: [['票', 'piào', 'ticket'], ['漂', 'piào', 'pretty'], ['飘', 'piāo', 'float']],
  pin: [['品', 'pǐn', 'product'], ['拼', 'pīn', 'spell']],
  ping: [['平', 'píng', 'flat'], ['苹', 'píng', 'apple'], ['瓶', 'píng', 'bottle'], ['评', 'píng', 'comment']],
  po: [['破', 'pò', 'break'], ['婆', 'pó', 'grandma']],
  pu: [['普', 'pǔ', 'universal'], ['铺', 'pù', 'shop']],
  qi: [['七', 'qī', 'seven'], ['起', 'qǐ', 'rise'], ['气', 'qì', 'air'], ['其', 'qí', 'its'], ['奇', 'qí', 'strange'], ['期', 'qī', 'period'], ['器', 'qì', 'utensil'], ['骑', 'qí', 'ride']],
  qian: [['前', 'qián', 'front'], ['钱', 'qián', 'money'], ['千', 'qiān', 'thousand'], ['签', 'qiān', 'sign'], ['浅', 'qiǎn', 'shallow'], ['铅', 'qiān', 'lead']],
  qiang: [['强', 'qiáng', 'strong'], ['墙', 'qiáng', 'wall'], ['枪', 'qiāng', 'gun'], ['抢', 'qiǎng', 'grab']],
  qiao: [['桥', 'qiáo', 'bridge'], ['巧', 'qiǎo', 'clever'], ['敲', 'qiāo', 'knock'], ['悄', 'qiāo', 'quiet']],
  qie: [['切', 'qiē', 'cut'], ['且', 'qiě', 'and']],
  qin: [['亲', 'qīn', 'parent'], ['轻', 'qīng', 'light'], ['琴', 'qín', 'piano'], ['勤', 'qín', 'diligent']],
  qing: [['请', 'qǐng', 'please'], ['清', 'qīng', 'clear'], ['轻', 'qīng', 'light'], ['情', 'qíng', 'emotion'], ['晴', 'qíng', 'sunny'], ['青', 'qīng', 'green/blue']],
  qiu: [['球', 'qiú', 'ball'], ['秋', 'qiū', 'autumn'], ['求', 'qiú', 'seek']],
  qu: [['去', 'qù', 'go'], ['取', 'qǔ', 'take'], ['趣', 'qù', 'interest'], ['区', 'qū', 'area']],
  quan: [['全', 'quán', 'all'], ['权', 'quán', 'right'], ['圈', 'quān', 'circle'], ['拳', 'quán', 'fist'], ['劝', 'quàn', 'advise']],
  que: [['却', 'què', 'but'], ['确', 'què', 'indeed'], ['缺', 'quē', 'lack']],
  qun: [['群', 'qún', 'group'], ['裙', 'qún', 'skirt']],
  ran: [['然', 'rán', 'so'], ['染', 'rǎn', 'dye']],
  rang: [['让', 'ràng', 'let'], ['嚷', 'rǎng', 'shout']],
  rao: [['绕', 'rào', 'surround']],
  re: [['热', 'rè', 'hot']],
  ren: [['人', 'rén', 'person'], ['认', 'rèn', 'recognize'], ['任', 'rèn', 'assign'], ['忍', 'rěn', 'endure']],
  reng: [['仍', 'réng', 'still'], ['扔', 'rēng', 'throw']],
  ri: [['日', 'rì', 'day/sun']],
  rong: [['容', 'róng', 'contain'], ['荣', 'róng', 'glory'], ['融', 'róng', 'melt']],
  rou: [['肉', 'ròu', 'meat'], ['柔', 'róu', 'soft']],
  ru: [['如', 'rú', 'like'], ['入', 'rù', 'enter']],
  ruan: [['软', 'ruǎn', 'soft']],
  san: [['三', 'sān', 'three'], ['散', 'sàn', 'scatter'], ['伞', 'sǎn', 'umbrella']],
  sao: [['扫', 'sǎo', 'sweep'], ['嫂', 'sǎo', 'sister-in-law']],
  se: [['色', 'sè', 'color']],
  sen: [['森', 'sēn', 'forest']],
  sha: [['杀', 'shā', 'kill'], ['沙', 'shā', 'sand'], ['傻', 'shǎ', 'silly']],
  shai: [['晒', 'shài', 'dry in sun']],
  shan: [['山', 'shān', 'mountain'], ['善', 'shàn', 'good'], ['扇', 'shàn', 'fan'], ['闪', 'shǎn', 'flash']],
  shang: [['上', 'shàng', 'up'], ['伤', 'shāng', 'hurt'], ['商', 'shāng', 'commerce']],
  shao: [['少', 'shǎo', 'few'], ['烧', 'shāo', 'burn'], ['勺', 'sháo', 'spoon']],
  she: [['社', 'shè', 'society'], ['蛇', 'shé', 'snake'], ['舌', 'shé', 'tongue'], ['设', 'shè', 'set up'], ['射', 'shè', 'shoot']],
  shei: [['谁', 'shéi', 'who']],
  shen: [['什', 'shén', 'what'], ['身', 'shēn', 'body'], ['深', 'shēn', 'deep'], ['神', 'shén', 'god'], ['生', 'shēng', 'born'], ['甚', 'shèn', 'very']],
  sheng: [['生', 'shēng', 'born'], ['声', 'shēng', 'sound'], ['省', 'shěng', 'province'], ['胜', 'shèng', 'win'], ['圣', 'shèng', 'holy'], ['剩', 'shèng', 'remain']],
  shi: [['是', 'shì', 'is'], ['十', 'shí', 'ten'], ['时', 'shí', 'time'], ['事', 'shì', 'matter'], ['世', 'shì', 'world'], ['市', 'shì', 'city'], ['石', 'shí', 'stone'], ['食', 'shí', 'food'], ['室', 'shì', 'room'], ['试', 'shì', 'try'], ['式', 'shì', 'style']],
  shou: [['手', 'shǒu', 'hand'], ['收', 'shōu', 'receive'], ['首', 'shǒu', 'head'], ['受', 'shòu', 'receive'], ['瘦', 'shòu', 'thin'], ['守', 'shǒu', 'guard']],
  shu: [['书', 'shū', 'book'], ['树', 'shù', 'tree'], ['数', 'shù', 'number'], ['熟', 'shú', 'ripe'], ['输', 'shū', 'lose'], ['属', 'shǔ', 'belong'], ['鼠', 'shǔ', 'mouse']],
  shua: [['刷', 'shuā', 'brush']],
  shuai: [['帅', 'shuài', 'handsome'], ['摔', 'shuāi', 'fall']],
  shuan: [['拴', 'shuān', 'tie']],
  shuang: [['双', 'shuāng', 'double'], ['爽', 'shuǎng', 'refreshing']],
  shui: [['水', 'shuǐ', 'water'], ['睡', 'shuì', 'sleep'], ['税', 'shuì', 'tax']],
  shun: [['顺', 'shùn', 'smooth']],
  shuo: [['说', 'shuō', 'speak'], ['硕', 'shuò', 'large']],
  si: [['四', 'sì', 'four'], ['死', 'sǐ', 'die'], ['思', 'sī', 'think'], ['司', 'sī', 'department'], ['私', 'sī', 'private'], ['丝', 'sī', 'silk']],
  song: [['送', 'sòng', 'send'], ['松', 'sōng', 'pine/loose']],
  sou: [['搜', 'sōu', 'search']],
  su: [['速', 'sù', 'speed'], ['素', 'sù', 'plain'], ['诉', 'sù', 'tell'], ['宿', 'sù', 'lodge'], ['酸', 'suān', 'sour']],
  suan: [['算', 'suàn', 'calculate'], ['酸', 'suān', 'sour']],
  sui: [['岁', 'suì', 'age'], ['随', 'suí', 'follow'], ['碎', 'suì', 'broken']],
  sun: [['孙', 'sūn', 'grandchild'], ['损', 'sǔn', 'damage']],
  suo: [['所', 'suǒ', 'place'], ['锁', 'suǒ', 'lock']],
  ta: [['他', 'tā', 'he'], ['她', 'tā', 'she'], ['它', 'tā', 'it'], ['塔', 'tǎ', 'tower'], ['踏', 'tà', 'step']],
  tai: [['太', 'tài', 'too'], ['台', 'tái', 'platform'], ['态', 'tài', 'attitude'], ['抬', 'tái', 'raise']],
  tan: [['谈', 'tán', 'talk'], ['弹', 'tán', 'play'], ['叹', 'tàn', 'sigh'], ['探', 'tàn', 'explore'], ['碳', 'tàn', 'carbon']],
  tang: [['汤', 'tāng', 'soup'], ['糖', 'táng', 'sugar'], ['堂', 'táng', 'hall'], ['躺', 'tǎng', 'lie down'], ['烫', 'tàng', 'hot/burn']],
  tao: [['桃', 'táo', 'peach'], ['逃', 'táo', 'escape'], ['讨', 'tǎo', 'discuss'], ['套', 'tào', 'set']],
  te: [['特', 'tè', 'special']],
  teng: [['疼', 'téng', 'pain']],
  ti: [['提', 'tí', 'raise'], ['题', 'tí', 'topic'], ['体', 'tǐ', 'body'], ['替', 'tì', 'replace'], ['踢', 'tī', 'kick']],
  tian: [['天', 'tiān', 'sky/day'], ['田', 'tián', 'field'], ['甜', 'tián', 'sweet'], ['填', 'tián', 'fill']],
  tiao: [['条', 'tiáo', 'strip'], ['跳', 'tiào', 'jump'], ['调', 'tiáo', 'adjust']],
  tie: [['铁', 'tiě', 'iron'], ['贴', 'tiē', 'paste']],
  ting: [['听', 'tīng', 'listen'], ['停', 'tíng', 'stop'], ['挺', 'tǐng', 'straight'], ['庭', 'tíng', 'court']],
  tong: [['同', 'tóng', 'same'], ['通', 'tōng', 'through'], ['痛', 'tòng', 'pain'], ['统', 'tǒng', 'unite'], ['铜', 'tóng', 'copper']],
  tou: [['头', 'tóu', 'head'], ['偷', 'tōu', 'steal'], ['透', 'tòu', 'through']],
  tu: [['土', 'tǔ', 'earth'], ['图', 'tú', 'picture'], ['突', 'tū', 'sudden'], ['吐', 'tǔ', 'spit'], ['兔', 'tù', 'rabbit']],
  tuan: [['团', 'tuán', 'group']],
  tui: [['退', 'tuì', 'retreat'], ['推', 'tuī', 'push'], ['腿', 'tuǐ', 'leg']],
  tuo: [['脱', 'tuō', 'take off'], ['拖', 'tuō', 'drag']],
  wa: [['挖', 'wā', 'dig'], ['哇', 'wa', 'wow'], ['娃', 'wá', 'baby'], ['袜', 'wà', 'sock']],
  wai: [['外', 'wài', 'outside'], ['歪', 'wāi', 'crooked']],
  wan: [['万', 'wàn', 'ten thousand'], ['完', 'wán', 'finish'], ['晚', 'wǎn', 'late'], ['玩', 'wán', 'play'], ['碗', 'wǎn', 'bowl'], ['弯', 'wān', 'bend']],
  wang: [['王', 'wáng', 'king'], ['网', 'wǎng', 'net'], ['往', 'wǎng', 'toward'], ['忘', 'wàng', 'forget'], ['望', 'wàng', 'gaze']],
  wei: [['为', 'wèi', 'for'], ['位', 'wèi', 'position'], ['围', 'wéi', 'surround'], ['味', 'wèi', 'taste'], ['未', 'wèi', 'not yet'], ['伟', 'wěi', 'great'], ['微', 'wēi', 'tiny'], ['危', 'wēi', 'danger']],
  wen: [['问', 'wèn', 'ask'], ['文', 'wén', 'writing'], ['闻', 'wén', 'hear'], ['温', 'wēn', 'warm'], ['稳', 'wěn', 'stable']],
  wo: [['我', 'wǒ', 'I/me'], ['握', 'wò', 'hold']],
  wu: [['五', 'wǔ', 'five'], ['无', 'wú', 'none'], ['物', 'wù', 'thing'], ['雾', 'wù', 'fog'], ['误', 'wù', 'mistake'], ['午', 'wǔ', 'noon'], ['舞', 'wǔ', 'dance'], ['武', 'wǔ', 'martial']],
  xi: [['西', 'xī', 'west'], ['习', 'xí', 'practice'], ['喜', 'xǐ', 'happy'], ['洗', 'xǐ', 'wash'], ['细', 'xì', 'thin'], ['系', 'xì', 'system'], ['戏', 'xì', 'play'], ['息', 'xī', 'rest']],
  xia: [['下', 'xià', 'down'], ['夏', 'xià', 'summer'], ['吓', 'xià', 'scare'], ['虾', 'xiā', 'shrimp']],
  xian: [['先', 'xiān', 'first'], ['现', 'xiàn', 'present'], ['线', 'xiàn', 'line'], ['鲜', 'xiān', 'fresh'], ['显', 'xiǎn', 'show'], ['限', 'xiàn', 'limit'], ['险', 'xiǎn', 'danger']],
  xiang: [['想', 'xiǎng', 'think'], ['向', 'xiàng', 'toward'], ['像', 'xiàng', 'resemble'], ['香', 'xiāng', 'fragrant'], ['乡', 'xiāng', 'village'], ['相', 'xiāng', 'mutual'], ['响', 'xiǎng', 'sound'], ['箱', 'xiāng', 'box']],
  xiao: [['小', 'xiǎo', 'small'], ['笑', 'xiào', 'laugh'], ['校', 'xiào', 'school'], ['消', 'xiāo', 'disappear'], ['效', 'xiào', 'effect']],
  xie: [['写', 'xiě', 'write'], ['谢', 'xiè', 'thank'], ['些', 'xiē', 'some'], ['鞋', 'xié', 'shoe'], ['血', 'xiě', 'blood']],
  xin: [['心', 'xīn', 'heart'], ['新', 'xīn', 'new'], ['信', 'xìn', 'believe'], ['星', 'xīng', 'star'], ['辛', 'xīn', 'hard']],
  xing: [['行', 'xíng', 'walk'], ['星', 'xīng', 'star'], ['姓', 'xìng', 'surname'], ['性', 'xìng', 'nature'], ['醒', 'xǐng', 'wake'], ['兴', 'xìng', 'excitement'], ['幸', 'xìng', 'lucky'], ['形', 'xíng', 'shape']],
  xiong: [['兄', 'xiōng', 'brother'], ['熊', 'xióng', 'bear'], ['胸', 'xiōng', 'chest']],
  xiu: [['休', 'xiū', 'rest'], ['修', 'xiū', 'repair'], ['秀', 'xiù', 'show']],
  xu: [['需', 'xū', 'need'], ['许', 'xǔ', 'allow'], ['续', 'xù', 'continue']],
  xuan: [['选', 'xuǎn', 'choose'], ['悬', 'xuán', 'hang']],
  xue: [['学', 'xué', 'study'], ['雪', 'xuě', 'snow'], ['血', 'xuè', 'blood']],
  xun: [['训', 'xùn', 'train'], ['寻', 'xún', 'seek']],
  ya: [['呀', 'ya', 'ah'], ['压', 'yā', 'press'], ['牙', 'yá', 'tooth'], ['鸭', 'yā', 'duck']],
  yan: [['眼', 'yǎn', 'eye'], ['言', 'yán', 'speak'], ['研', 'yán', 'research'], ['烟', 'yān', 'smoke'], ['盐', 'yán', 'salt'], ['严', 'yán', 'strict'], ['颜', 'yán', 'color']],
  yang: [['样', 'yàng', 'shape'], ['阳', 'yáng', 'sun'], ['养', 'yǎng', 'raise'], ['羊', 'yáng', 'sheep']],
  yao: [['要', 'yào', 'want'], ['药', 'yào', 'medicine'], ['摇', 'yáo', 'shake'], ['咬', 'yǎo', 'bite']],
  ye: [['也', 'yě', 'also'], ['夜', 'yè', 'night'], ['叶', 'yè', 'leaf'], ['业', 'yè', 'business'], ['爷', 'yé', 'grandpa']],
  yi: [['一', 'yī', 'one'], ['以', 'yǐ', 'with'], ['已', 'yǐ', 'already'], ['意', 'yì', 'meaning'], ['衣', 'yī', 'clothes'], ['医', 'yī', 'doctor'], ['易', 'yì', 'easy'], ['义', 'yì', 'justice'], ['亿', 'yì', 'hundred million'], ['艺', 'yì', 'art']],
  yin: [['因', 'yīn', 'because'], ['音', 'yīn', 'sound'], ['银', 'yín', 'silver'], ['引', 'yǐn', 'lead'], ['印', 'yìn', 'print'], ['阴', 'yīn', 'cloudy']],
  ying: [['应', 'yīng', 'should'], ['英', 'yīng', 'hero'], ['影', 'yǐng', 'shadow'], ['赢', 'yíng', 'win'], ['营', 'yíng', 'camp'], ['迎', 'yíng', 'welcome'], ['硬', 'yìng', 'hard']],
  yong: [['用', 'yòng', 'use'], ['永', 'yǒng', 'forever'], ['勇', 'yǒng', 'brave'], ['拥', 'yōng', 'embrace']],
  you: [['有', 'yǒu', 'have'], ['又', 'yòu', 'again'], ['右', 'yòu', 'right'], ['友', 'yǒu', 'friend'], ['游', 'yóu', 'swim'], ['油', 'yóu', 'oil'], ['由', 'yóu', 'from'], ['优', 'yōu', 'excellent']],
  yu: [['于', 'yú', 'at'], ['鱼', 'yú', 'fish'], ['雨', 'yǔ', 'rain'], ['语', 'yǔ', 'language'], ['与', 'yǔ', 'and'], ['玉', 'yù', 'jade'], ['遇', 'yù', 'meet'], ['育', 'yù', 'educate'], ['预', 'yù', 'advance']],
  yuan: [['元', 'yuán', 'yuan'], ['远', 'yuǎn', 'far'], ['原', 'yuán', 'origin'], ['院', 'yuàn', 'yard'], ['愿', 'yuàn', 'wish'], ['圆', 'yuán', 'round'], ['源', 'yuán', 'source']],
  yue: [['月', 'yuè', 'moon'], ['越', 'yuè', 'exceed'], ['约', 'yuē', 'about'], ['乐', 'yuè', 'music'], ['阅', 'yuè', 'read']],
  yun: [['云', 'yún', 'cloud'], ['运', 'yùn', 'transport'], ['允', 'yǔn', 'allow']],
  za: [['杂', 'zá', 'mixed'], ['砸', 'zá', 'smash']],
  zai: [['在', 'zài', 'at'], ['再', 'zài', 'again'], ['灾', 'zāi', 'disaster']],
  zan: [['咱', 'zán', 'we'], ['赞', 'zàn', 'praise']],
  zang: [['脏', 'zāng', 'dirty']],
  zao: [['早', 'zǎo', 'early'], ['造', 'zào', 'make'], ['糟', 'zāo', 'messy'], ['澡', 'zǎo', 'bath']],
  ze: [['则', 'zé', 'rule'], ['责', 'zé', 'duty']],
  zen: [['怎', 'zěn', 'how']],
  zeng: [['增', 'zēng', 'increase']],
  zha: [['炸', 'zhà', 'fry'], ['扎', 'zhā', 'prick']],
  zhai: [['窄', 'zhǎi', 'narrow'], ['摘', 'zhāi', 'pick']],
  zhan: [['站', 'zhàn', 'stand'], ['战', 'zhàn', 'war'], ['占', 'zhàn', 'occupy'], ['展', 'zhǎn', 'expand']],
  zhang: [['张', 'zhāng', 'open/Zhang'], ['长', 'zhǎng', 'grow'], ['章', 'zhāng', 'chapter'], ['掌', 'zhǎng', 'palm']],
  zhao: [['找', 'zhǎo', 'find'], ['着', 'zháo', 'touch'], ['照', 'zhào', 'shine']],
  zhe: [['这', 'zhè', 'this'], ['着', 'zhe', 'particle'], ['者', 'zhě', 'person']],
  zhen: [['真', 'zhēn', 'real'], ['针', 'zhēn', 'needle'], ['阵', 'zhèn', 'battle'], ['震', 'zhèn', 'shake'], ['珍', 'zhēn', 'precious']],
  zheng: [['正', 'zhèng', 'correct'], ['整', 'zhěng', 'whole'], ['争', 'zhēng', 'compete'], ['证', 'zhèng', 'prove'], ['政', 'zhèng', 'politics']],
  zhi: [['只', 'zhǐ', 'only'], ['知', 'zhī', 'know'], ['之', 'zhī', 'of'], ['直', 'zhí', 'straight'], ['值', 'zhí', 'value'], ['指', 'zhǐ', 'point'], ['纸', 'zhǐ', 'paper'], ['至', 'zhì', 'to'], ['制', 'zhì', 'make'], ['治', 'zhì', 'govern']],
  zhong: [['中', 'zhōng', 'middle'], ['种', 'zhǒng', 'kind'], ['重', 'zhòng', 'heavy'], ['钟', 'zhōng', 'clock'], ['众', 'zhòng', 'crowd']],
  zhou: [['周', 'zhōu', 'week'], ['州', 'zhōu', 'state'], ['粥', 'zhōu', 'porridge']],
  zhu: [['主', 'zhǔ', 'main'], ['住', 'zhù', 'live'], ['注', 'zhù', 'note'], ['猪', 'zhū', 'pig'], ['竹', 'zhú', 'bamboo'], ['祝', 'zhù', 'wish'], ['助', 'zhù', 'help']],
  zhua: [['抓', 'zhuā', 'grab']],
  zhuang: [['装', 'zhuāng', 'install'], ['壮', 'zhuàng', 'strong'], ['撞', 'zhuàng', 'hit']],
  zhui: [['追', 'zhuī', 'chase']],
  zhun: [['准', 'zhǔn', 'allow']],
  zhuo: [['桌', 'zhuō', 'table'], ['着', 'zhuó', 'wear']],
  zi: [['子', 'zǐ', 'child'], ['字', 'zì', 'character'], ['自', 'zì', 'self'], ['紫', 'zǐ', 'purple']],
  zong: [['总', 'zǒng', 'always'], ['宗', 'zōng', 'ancestor']],
  zou: [['走', 'zǒu', 'walk'], ['奏', 'zòu', 'play']],
  zu: [['组', 'zǔ', 'group'], ['足', 'zú', 'foot'], ['族', 'zú', 'clan'], ['阻', 'zǔ', 'block'], ['祖', 'zǔ', 'ancestor']],
  zuan: [['钻', 'zuān', 'drill']],
  zui: [['最', 'zuì', 'most'], ['醉', 'zuì', 'drunk'], ['罪', 'zuì', 'crime'], ['嘴', 'zuǐ', 'mouth']],
  zuo: [['做', 'zuò', 'do'], ['坐', 'zuò', 'sit'], ['左', 'zuǒ', 'left'], ['座', 'zuò', 'seat'], ['作', 'zuò', 'work']],
};

// Build reverse lookup: character → { pinyin, meaning }
export const CHAR_INFO: Record<string, { pinyin: string; meaning: string }> = {};
for (const entries of Object.values(PINYIN_MAP)) {
  for (const [char, pinyin, meaning] of entries) {
    if (!CHAR_INFO[char]) {
      CHAR_INFO[char] = { pinyin, meaning };
    }
  }
}

// Common phrase translations
export const PHRASE_DICT: Record<string, string> = {
  '你好': 'hello',
  '谢谢': 'thank you',
  '再见': 'goodbye',
  '对不起': 'sorry',
  '没关系': "it's okay",
  '不客气': "you're welcome",
  '早上好': 'good morning',
  '晚上好': 'good evening',
  '晚安': 'good night',
  '我爱你': 'I love you',
  '中国': 'China',
  '美国': 'America',
  '朋友': 'friend',
  '学生': 'student',
  '老师': 'teacher',
  '大学': 'university',
  '学校': 'school',
  '工作': 'work',
  '电话': 'telephone',
  '电脑': 'computer',
  '手机': 'cellphone',
  '今天': 'today',
  '明天': 'tomorrow',
  '昨天': 'yesterday',
  '吃饭': 'eat',
  '喝水': 'drink water',
  '睡觉': 'sleep',
  '看书': 'read a book',
  '什么': 'what',
  '怎么': 'how',
  '为什么': 'why',
  '多少': 'how much',
  '漂亮': 'beautiful',
  '高兴': 'happy',
  '快乐': 'happy',
  '开心': 'happy',
  '好吃': 'delicious',
  '可以': 'can/may',
  '知道': 'know',
  '喜欢': 'like',
  '非常': 'very much',
  '一起': 'together',
  '时候': 'time/when',
  '现在': 'now',
  '以后': 'later',
  '以前': 'before',
  '已经': 'already',
  '还是': 'or/still',
  '但是': 'but',
  '因为': 'because',
  '所以': 'so/therefore',
  '如果': 'if',
  '虽然': 'although',
  '可能': 'maybe',
  '应该': 'should',
  '需要': 'need',
  '希望': 'hope',
  '觉得': 'feel/think',
  '认为': 'think/believe',
  '帮助': 'help',
  '问题': 'question',
  '回答': 'answer',
  '生活': 'life',
  '东西': 'thing',
  '地方': 'place',
  '身体': 'body',
  '天气': 'weather',
  '中文': 'Chinese language',
  '英文': 'English language',
  '练习': 'practice',
  '汉字': 'Chinese character',
};

// Set of all valid pinyin syllables for splitting
export const ALL_SYLLABLES = new Set(Object.keys(PINYIN_MAP));
